packages:
  - impl/**
  - book/playground
  - "!examples/vuejs-core"

catalog:
  vite: npm:@voidzero-dev/vite-plus-core@^0.3.2
  vite-plus: ^0.3.3
  vitest: ^4.1.11

overrides:
  vite: "catalog:"
  vitest: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
